---
- name: Remove 'no valid subscript' message
  ansible.builtin.shell:
    cmd: |
      sed -Ezi.backup "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
  notify: Restart pveproxy
